http:
  server:
    port: 8080
    path: /platform
rsocket:
  server:
    webSocketPort: 9001
tarantool:
  configurations:
    platform:
      connection:
        host: 185.155.19.36
        port: 3301
        username: username
        password: password
      instanceMode: local

